# Generated by Django 2.1.7 on 2019-03-03 23:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 3, 23, 14, 58, 518094), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 3, 23, 14, 58, 518094), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='tutorial2',
            name='tutorial2_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 3, 23, 14, 58, 519092), verbose_name='date published'),
        ),
    ]
