# Generated by Django 2.1.7 on 2019-03-03 23:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190303_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 3, 23, 20, 2, 143088), verbose_name='date published'),
        ),
    ]
